# Generated by Django 3.2 on 2021-04-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('stud_class', models.CharField(max_length=40)),
                ('department', models.CharField(max_length=40)),
            ],
        ),
    ]
